# Generated by .github/workflows/update-pi.yml.
{
  darwin-arm64 = "186bc911b2jrwsc15pyhr1rkwah1p6b1vz7l7dg4gc662v3sf9mn";
  darwin-x64 = "0gzvjjfwv0fi0f16iy9ygd052ik9ia66sb78b53l0qls3jj3d6q6";
  linux-arm64 = "0sl3ln8lngpgfm9nbhg1hbyczrzqaifgndi9fwf9vvhfvyiwlcmx";
  linux-x64 = "17w444m10rr7clmjbfgqwc8rwb12jz1dpgbjp5v0kgknwqjpxh0k";
}
