# Generated by .github/workflows/update-pi.yml.
{
  darwin-arm64 = "0rsb48jbkhd4zyy5sk3s4c57smy2mgys823kr42jbl3mq58d11ld";
  darwin-x64 = "1v58b19sqjvzjq581vd8gbj6l8snlh0w8spaa4w6iaacg684pn8s";
  linux-arm64 = "0awal5q28qrhll3bkd7h8zg4rc1s9y1dw6rsaqjhni1dsr0ds04d";
  linux-x64 = "0lr8xql54lrvw8p8d92v9z8bgcj799h19fblx8rc172f5hz4cy22";
}
