# Generated by .github/workflows/update-pi.yml.
{
  darwin-arm64 = "1196x249z75j96w8fmaycrqw3kw4p45v09gljjbfq42w7m4a9pz1";
  darwin-x64 = "1p2ashnp67snjw42r9pfnplzfhc13ydi1nv4w7xnsf6pyb1s5bkn";
  linux-arm64 = "09ghswhrgrpr6ci8203yyv6a9692v7gki4r2qpn4j0249bncrli7";
  linux-x64 = "0dq7y7ykayd8wy14sxmv4v6r605nrasm702az57z41jsxjrz6m5b";
}
